name: Build and Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd TiendaProductosElectronicos
          npm install

      - name: Build Angular project
        run: |
          cd TiendaProductosElectronicos
          npm run build -- --output-path=dist/tienda-productos-electronicos --base-href=/garcia_conde_jose_DWEC06_TE01/

      - name: Show build log if fails
        run: |
          cd TiendaProductosElectronicos
          ls -l dist/tienda-productos-electronicos || echo "NO HAY CARPETA DE BUILD"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./TiendaProductosElectronicos/dist/tienda-productos-electronicos
